name: SimpleChatFormat
version: '${version}'
main: me.almana.simplechatformat.SimpleChatFormat
api-version: '1.20'
depend:
  - LuckPerms
commands:
  formats:
    description: Core command of the plugin
    permission: chat.formatscmd
    aliases:
      - chatformats
